Repository liquidweb/woocommerce-custom-orders-table, pull requests merged in 2020-02, with the labels that each got.

#154 Bump dependencies
  .travis.yml
  composer.json
  composer.lock
  includes/class-wc-customer-data-store-custom-table.php
  includes/class-wc-order-data-store-custom-table.php
  includes/class-woocommerce-custom-orders-table-cli.php
  phpunit.xml.dist
  tests/bin/install-woocommerce.sh
  tests/bin/set-woocommerce-version.sh
  tests/bootstrap.php
Labels: code quality, testing

#152 Add support for --batch-size=0 to CLI commands
  README.md
  includes/class-woocommerce-custom-orders-table-cli.php
  tests/test-cli.php
Labels: cli migration, enhancement

#157 Use offsets with migration queries
  includes/class-woocommerce-custom-orders-table-cli.php
  tests/test-cli.php
Labels: bug, cli migration, code quality

#106 Improve test coverage
  includes/class-woocommerce-custom-orders-table-cli.php
  tests/test-bootstrap.php
  tests/test-cli.php
  tests/test-customer-data-store.php
  tests/test-order-data-store.php
Labels: testing

#158 Added README + assets
  assets/banner-1544x500.jpg
  assets/banner-772x250.jpg
  assets/icon-128x128.jpg
  assets/icon-256x256.jpg
  assets/woocommerce-custom-orders-table-icon.psd
  assets/woocommerce-custom-orders-table.psd
  readme.txt
Labels: documentation
